### ISSUE TITLE
where is log file?

### ISSUE THREAD

**Issue by yaboroda** [stanleywuu/vscode-timetracker#1]
Hi! Love this extension. Only one thing bothering me. You wrote that "the log file grows indefinitely" but didn't wrote where i can find this file to manage it.

**Comment by stanleywuu** [comment]
Thank you for using my extension.
To help you manage the files, 
I have created a new command vstime: Open Current Logs and vstime: Reset

But as far as your question goes, if you are using a linux system, it would live under
~/.config/Code/User/globalStorage/swuvsmarket.vstime/

On a windows system, you can find the files at

C:\Users\{username}\AppData\Roaming\Code\User\globalStorage\swuvsmarket.vstime\

You might need to show hidden or ls -a the file name is .vstime.

This weekend, I can look into making the filename configurable.

Thank you very much for using my extension.

**Comment by yaboroda** [comment]
Thanks alot! And once again, great extension ))
