### ISSUE TITLE
yesterday panel

### ISSUE THREAD

**Issue by yaboroda** [stanleywuu/vscode-timetracker#2]
Hi, it's me again! If not much trouble could you add third panel for "yesterday". It would be very helpful for morning daily meetings in zoom. Thanks!

**Comment by stanleywuu** [comment]
Hi, I made an update to show a yesterday panel.
Glad I can help!

Again, thank you for using the extension.

**Comment by yaboroda** [comment]
Thanks! Now it is nearly perfect ))
If you want me to, I could provide some more feature requests. But for my use case it completely suitable as it is.

**Comment by stanleywuu** [comment]
Sweet! Please shoot me the feature requests, I just might do them one of these days :)

**Comment by yaboroda** [comment]
'yesterday' panel isnt working (see screenshot)
![image](https://user-images.githubusercontent.com/28389844/119502564-ba08ea80-bd72-11eb-8fb7-52ddb11b705e.png)

**Comment by stanleywuu** [comment]
Sorry could you send me your .vstime file so I can test it?
I tried changing time on my computer and wasn't able to reproduce this.

**Comment by yaboroda** [comment]
Sory, i'm under very strict NDA. A cant pass you file with real files structure, so i will replace file path with blablabla, hope it will not obstruct your work. Also i add .log to filename in order to github permits me upload file ))
[vstime.log](https://github.com/stanleywuu/vscode-timetracker/files/6539784/vstime.log)

**Comment by stanleywuu** [comment]
![image](https://user-images.githubusercontent.com/1847313/119518911-f4f52900-bd46-11eb-9311-bf34be037dad.png)
weird, this is working for me, too.

I'll try on Windows later today.

Did you have VSCode open the entire time?
I'm wondering if it's a refresh issue, I fixed up the refresh button in version 0.3.9 to refresh all panels.

**Comment by yaboroda** [comment]
Updated extension and it works now! Thanks ))

`Did you have VSCode open the entire time?`
Yes I did. Also my laptop was falling to sleep and awakes several times.

`I'll try on Windows later today`
It wouldn't be much use for my case. I work on linux and macos.
